import Nav from '@/components/navbar/Nav'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import { ThemeProvider } from '@/context/ThemeContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <div className="container">
          <div className="wrapper px-20 ">
            <Nav/>
            {children}
           <Footer /> {/* Render the Footer conditionally */}
          </div>
        </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
